package dev.tobyscamera.folia.storage;
import dev.tobyscamera.common.upload.VideoUploadSession; import java.io.*; import java.nio.file.*; import java.sql.*; import java.time.Instant; import java.util.*;
public final class SqliteVideoRepository implements AutoCloseable {
 private final Path directory; private final Connection connection;
 public SqliteVideoRepository(Path root) throws IOException { try { directory=Files.createDirectories(root.resolve("videos")); connection=DriverManager.getConnection("jdbc:sqlite:"+root.resolve("videos.db").toAbsolutePath()); try(var s=connection.createStatement()){s.executeUpdate("create table if not exists videos(id text primary key, owner text, created integer, width integer, height integer, fps integer, frames integer)");s.executeUpdate("create table if not exists video_maps(video_id text,x integer,y integer,map_id integer,primary key(video_id,x,y))");} }catch(SQLException e){throw new IOException(e);} }
 public synchronized void save(VideoRecord r, VideoUploadSession s) throws IOException { try { Path d=Files.createDirectories(directory.resolve(r.videoId().toString())); for(int f=0;f<r.frameCount();f++)for(int y=0;y<r.gridHeight();y++)for(int x=0;x<r.gridWidth();x++)Files.write(d.resolve(f+"-"+x+"-"+y+".tile"), tile(s,f,x,y)); try(var p=connection.prepareStatement("insert into videos values(?,?,?,?,?,?,?)");var m=connection.prepareStatement("insert into video_maps values(?,?,?,?)")){p.setString(1,r.videoId().toString());p.setString(2,r.ownerId().toString());p.setLong(3,r.createdAt().toEpochMilli());p.setInt(4,r.gridWidth());p.setInt(5,r.gridHeight());p.setInt(6,r.fps());p.setInt(7,r.frameCount());p.executeUpdate();for(var e:r.mapIds().entrySet()){m.setString(1,r.videoId().toString());m.setInt(2,e.getKey().x());m.setInt(3,e.getKey().y());m.setInt(4,e.getValue());m.addBatch();}m.executeBatch();}}catch(SQLException e){throw new IOException(e);} }
 private static byte[] tile(VideoUploadSession s,int f,int x,int y){ return s.tile(f,x,y); }
 public List<VideoRecord> loadAll() throws IOException { try(var q=connection.createStatement();var rs=q.executeQuery("select * from videos")){var out=new ArrayList<VideoRecord>();while(rs.next()){UUID id=UUID.fromString(rs.getString(1));var maps=new LinkedHashMap<TileCoordinate,Integer>();try(var m=connection.prepareStatement("select x,y,map_id from video_maps where video_id=?")){m.setString(1,id.toString());var r=m.executeQuery();while(r.next())maps.put(new TileCoordinate(r.getInt(1),r.getInt(2)),r.getInt(3));}out.add(new VideoRecord(id,UUID.fromString(rs.getString(2)),Instant.ofEpochMilli(rs.getLong(3)),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),maps));}return out;}catch(SQLException e){throw new IOException(e);} }
 public byte[] readTile(UUID id,int frame,TileCoordinate c)throws IOException{return Files.readAllBytes(directory.resolve(id.toString()).resolve(frame+"-"+c.x()+"-"+c.y()+".tile"));} public void close()throws IOException{try{connection.close();}catch(SQLException e){throw new IOException(e);}}
}
